import type { ElevationTransform, SubmitFloodSimulationRequest } from '../api';
// Paths are relative to the flood-engine worker process's cwd (flood-engine/),
// generated by `python -m flood_engine.cli.prepare_demo_scenario` from real
// windowed Mumbai SRTM DEM + ESA WorldCover + OSM building data. All values
// below (bounds, transform, EPSG) are copied verbatim from the real
// flood-engine/demo-data/provenance.json that run produced -- not invented.
const DEMO_ARRAY_DIR = 'demo-data';
const DEMO_AOI_BOUNDS_WGS84: readonly [number, number, number, number] = [
  72.86067977484046, 19.064587966153745, 72.89372739340703, 19.097566255000096,
];
const DEMO_ELEVATION_TRANSFORM: ElevationTransform = [
  29.112099545888267, 0.0, 274926.44163190015, 0.0, -29.112099545888267, 2112956.563385692,
];
const DEMO_ELEVATION_CRS_EPSG = 32643;
export const DEMO_FLOOD_SIMULATION_REQUEST: SubmitFloodSimulationRequest = {
  scenarioId: 'vektra-demo',
  elevationPath: `${DEMO_ARRAY_DIR}/elevation.npy`,
  buildingMaskPath: `${DEMO_ARRAY_DIR}/building_mask.npy`,
  manningNPath: `${DEMO_ARRAY_DIR}/manning_n.npy`,
  infiltrationLossPath: `${DEMO_ARRAY_DIR}/infiltration.npy`,
  rainfallRatesPath: `${DEMO_ARRAY_DIR}/rainfall.npy`,
  aoiBoundsWgs84: DEMO_AOI_BOUNDS_WGS84,
  elevationTransform: DEMO_ELEVATION_TRANSFORM,
  elevationCrsEpsg: DEMO_ELEVATION_CRS_EPSG,
};
