-- VEKTRA Database — Consolidated Schema
-- Generated by concatenating db/migrations/0001_*.sql through 0015_*.sql, in order.
-- This file represents the current full schema for convenience (e.g. `psql -f db/schema.sql`
-- against a fresh database). db/migrations/ remains the source of truth and the
-- incremental history; if a new migration is added, this file must be regenerated
-- to stay in sync (see db/README.md).
--
-- EDD reference: Section 16 (Database Conceptual Model — entity level only, no
-- DDL specified there); this file is the implementation-level DDL derived from it.

-- ============================================================================
-- 0001_extensions.sql
-- ============================================================================
-- VEKTRA Database — Migration 0001
-- Enables required PostgreSQL extensions.
-- EDD reference: Section 12 (Technology Stack — PostgreSQL + PostGIS).
--
-- TODO: the exact target PostgreSQL version is "Not specified" in the EDD
-- (Section 12 states PostgreSQL + PostGIS is "already installed" without a
-- version number). This schema assumes PostgreSQL >= 13 and PostGIS >= 3.x
-- (required for gen_random_uuid() via pgcrypto and current PostGIS
-- function behavior). Verify against the actual deployment target before
-- applying in production.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 0002_common_functions.sql
-- ============================================================================
-- VEKTRA Database — Migration 0002
-- Shared trigger function enforcing the append-only / immutability
-- semantics of the Digital Twin State Model.
--
-- EDD reference: Section 15 (Digital Twin State Model), Section 7
-- (Determinism, Traceability non-functional requirements).
--
-- Section 15 states, for every layer of the state model, that data is
-- either "immutable once ingested" or "append-only" once computed, and
-- that this layering is what allows determinism and reproducibility "to
-- be satisfied structurally rather than by convention alone." This
-- migration is the structural enforcement mechanism: a BEFORE UPDATE
-- trigger that unconditionally rejects UPDATE statements on tables that
-- represent the static, environmental, or derived/computed layers.
--
-- Corrections to ingested or computed data must be made by inserting a
-- new, separately versioned row (a new provenance batch, a new
-- simulation run, etc.), never by editing an existing one in place.

CREATE OR REPLACE FUNCTION fn_prevent_update()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'table "%" is append-only per EDD Section 15; UPDATE is not permitted',
        TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_prevent_update() IS
    'Blocks UPDATE statements on append-only/immutable tables (EDD Section 15). '
    'Corrections must be made by inserting a new versioned row, never by editing an existing one.';

-- ============================================================================
-- 0003_data_source.sql
-- ============================================================================
-- VEKTRA Database — Migration 0003
-- data_source: closed lookup table enumerating the external data sources
-- listed in the EDD, used for referential integrity on
-- data_provenance_record.source_code.
--
-- This is NOT one of the entities named in EDD Section 16 — it is an
-- implementation-level normalization added so provenance rows cannot
-- reference an undocumented source. The set of rows it may ever contain
-- is closed by EDD Section 13 (Data Sources) and Section 8 (External
-- systems).
--
-- TomTom and Cesium ion are intentionally excluded from this table:
-- TomTom is an optional, currently unused future input whose use as a
-- heat-index input is explicitly "speculative" and "deferred to Section
-- 38" (Section 13); Cesium ion is 3D asset hosting/streaming, not a
-- dataset ingested into this database (Section 8, Section 20).

CREATE TABLE data_source (
    source_code   TEXT PRIMARY KEY,
    display_name  TEXT NOT NULL,
    license       TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_data_source_no_update
    BEFORE UPDATE ON data_source
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE data_source IS
    'Closed set of external data sources listed in EDD Section 13. Referenced by data_provenance_record.source_code.';
COMMENT ON COLUMN data_source.license IS
    'License/attribution requirement for this source, per EDD Section 24.';

-- ============================================================================
-- 0004_data_provenance_record.sql
-- ============================================================================
-- VEKTRA Database — Migration 0004
-- data_provenance_record: DataProvenanceRecord entity (EDD Section 16),
-- carrying the minimum required fields from the Data Provenance Strategy
-- (Section 24): source name, source product/scene/tile identifier,
-- retrieval timestamp, license/attribution, ingestion pipeline version,
-- and checksum "where feasible".
--
-- Design note — no separate "dataset_version" table:
-- EDD Section 27 (Versioning Strategy) defines "Dataset version" as
-- "every ingested batch is tagged with a version identifier (e.g., an
-- ingestion run timestamp plus source product identifiers)". That is
-- structurally identical to what this table already carries
-- (source_product_identifier + retrieval_timestamp), and EDD Section 16's
-- own stated relationship is that "every Building, EnvironmentalRasterAsset,
-- and MeteorologicalObservation references exactly one DataProvenanceRecord"
-- — singular, not a provenance reference plus a separate version reference.
-- Introducing a second, parallel "dataset_version" entity would duplicate
-- this table's fields and contradict that stated one-reference relationship.
-- The "dataset versions used by a SimulationRun" requirement (FR-12,
-- Section 17 point 3) is instead realized via the
-- simulation_run_input_dataset join table (migration 0009), which links a
-- run to the exact set of data_provenance_record rows it consumed.
-- See db/README.md for the full rationale.

CREATE TABLE data_provenance_record (
    provenance_id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_code                 TEXT NOT NULL REFERENCES data_source(source_code),
    source_product_identifier   TEXT NOT NULL,
    retrieval_timestamp         TIMESTAMPTZ NOT NULL,
    license                     TEXT NOT NULL,
    ingestion_pipeline_version  TEXT NOT NULL,
    checksum                    TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_provenance_batch
        UNIQUE (source_code, source_product_identifier, retrieval_timestamp)
);

CREATE INDEX idx_provenance_source_code ON data_provenance_record (source_code);
CREATE INDEX idx_provenance_retrieval_timestamp ON data_provenance_record (retrieval_timestamp);

CREATE TRIGGER trg_provenance_no_update
    BEFORE UPDATE ON data_provenance_record
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE data_provenance_record IS
    'DataProvenanceRecord (EDD Section 16, 24). Also fulfills the "dataset version" role described in Section 27 — see migration header.';
COMMENT ON COLUMN data_provenance_record.source_product_identifier IS
    'e.g. Landsat scene ID, Sentinel-2 tile ID, ESA WorldCover tile+version, OSM changeset or extract timestamp (Section 24).';
COMMENT ON COLUMN data_provenance_record.retrieval_timestamp IS
    'Ingestion time — when VEKTRA fetched the data, distinct from the data''s own observation/acquisition time (Section 26).';
COMMENT ON COLUMN data_provenance_record.checksum IS
    'Checksum of the retrieved artifact "where feasible" (Section 24); nullable by design.';

-- ============================================================================
-- 0005_building.sql
-- ============================================================================
-- VEKTRA Database — Migration 0005
-- building: Building entity, Static Geometric Layer (EDD Section 15, 16).
-- Represents one immutable, versioned snapshot of an OSM building
-- footprint as ingested for a given provenance batch (FR-1). Geometry is
-- never altered once ingested, by any process, under any circumstance
-- (Section 5, 9, 15) — enforced below by the append-only trigger, which
-- covers the whole row, not only the geometry columns, consistent with
-- Section 15's description of the whole static geometric layer as
-- "Immutable once ingested for a given OSM snapshot".
--
-- osm_type distinguishes OSM ways from multipolygon relations. This is a
-- factual property of the OpenStreetMap data model required to represent
-- footprints correctly under FR-1; it is not itself named in EDD Section
-- 16, but is necessary to ingest real OSM data without loss of structure.
--
-- Dual geometry columns implement the Section 14 Engineering Decision to
-- "store vector data in WGS84 (EPSG:4326) for interchange and in a
-- projected CRS suitable for metric analysis... UTM zone 43N (EPSG:32643)".
-- geom_utm43n is derived automatically from geom_wgs84 by the trigger
-- below when not supplied directly by the ingestion pipeline, because
-- PostGIS's ST_Transform() is STABLE (depends on spatial_ref_sys), not
-- IMMUTABLE, and therefore cannot be used in a GENERATED ALWAYS AS STORED
-- column expression.
--
-- footprint_area_sqm is a generated column (ST_Area is IMMUTABLE for
-- planar geometry) supporting the building morphology/density factor
-- input described in Section 18 (factor 3: "derived from footprint area...").

CREATE TABLE building (
    building_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    osm_id               BIGINT NOT NULL,
    osm_type             TEXT NOT NULL CHECK (osm_type IN ('way', 'relation')),
    building_tag_type    TEXT,
    name                 TEXT,
    height_m             NUMERIC CHECK (height_m IS NULL OR height_m > 0),
    building_levels      INTEGER CHECK (building_levels IS NULL OR building_levels > 0),
    geom_wgs84           geometry(MultiPolygon, 4326) NOT NULL,
    geom_utm43n          geometry(MultiPolygon, 32643),
    footprint_area_sqm   NUMERIC GENERATED ALWAYS AS (ST_Area(geom_utm43n)) STORED,
    provenance_id        UUID NOT NULL REFERENCES data_provenance_record(provenance_id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_building_osm_snapshot
        UNIQUE (osm_id, osm_type, provenance_id),
    CONSTRAINT chk_building_geom_wgs84_srid
        CHECK (ST_SRID(geom_wgs84) = 4326),
    CONSTRAINT chk_building_geom_utm43n_srid
        CHECK (geom_utm43n IS NULL OR ST_SRID(geom_utm43n) = 32643),
    CONSTRAINT chk_building_geom_wgs84_valid
        CHECK (ST_IsValid(geom_wgs84))
);

CREATE OR REPLACE FUNCTION fn_populate_building_utm_geometry()
RETURNS trigger AS $$
BEGIN
    IF NEW.geom_utm43n IS NULL THEN
        NEW.geom_utm43n := ST_Transform(NEW.geom_wgs84, 32643);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_populate_building_utm_geometry() IS
    'Derives the UTM 43N projected geometry from the canonical WGS84 geometry when not supplied directly (EDD Section 14).';

CREATE TRIGGER trg_building_populate_utm_geometry
    BEFORE INSERT ON building
    FOR EACH ROW EXECUTE FUNCTION fn_populate_building_utm_geometry();

CREATE TRIGGER trg_building_no_update
    BEFORE UPDATE ON building
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

CREATE INDEX idx_building_geom_wgs84_gist ON building USING GIST (geom_wgs84);
CREATE INDEX idx_building_geom_utm43n_gist ON building USING GIST (geom_utm43n);
CREATE INDEX idx_building_osm_id ON building (osm_id);
CREATE INDEX idx_building_provenance_id ON building (provenance_id);

COMMENT ON TABLE building IS
    'Building entity (EDD Section 16), Static Geometric Layer (Section 15). One row per versioned OSM footprint snapshot.';
COMMENT ON COLUMN building.height_m IS
    'OSM "height" tag. Completeness for the study area is unverified (Section 13); expect NULLs.';
COMMENT ON COLUMN building.building_levels IS
    'OSM "building:levels" tag. Completeness for the study area is unverified (Section 13); expect NULLs.';

-- ============================================================================
-- 0006_environmental_raster_asset.sql
-- ============================================================================
-- VEKTRA Database — Migration 0006
-- environmental_raster_asset: EnvironmentalRasterAsset entity
-- (EDD Section 16), Environmental Observation Layer (Section 15).
-- Metadata only — raw raster pixel data is NOT stored in PostGIS. Per
-- Section 16's stated Engineering Decision (open), "PostGIS metadata rows
-- reference files held in a separate object/file store"; the specific
-- object/file storage technology is "Not specified" and is left as a TODO
-- for the ingestion/infra layer. storage_location is therefore an opaque
-- reference string, not a typed path/URL, so this table does not assume a
-- particular storage technology.
--
-- spatial_extent (a bounding-box footprint geometry) is an addition not
-- explicitly named in Section 16, added because it is functionally
-- required to implement the "spatial overlay" mechanism Section 18
-- describes for attributing raster-derived factors (e.g. thermal
-- signature) to individual building footprints — without a stored extent,
-- there is no way to determine which raster assets cover which buildings.

CREATE TABLE environmental_raster_asset (
    raster_asset_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_code        TEXT NOT NULL REFERENCES data_source(source_code)
                            CHECK (source_code IN ('srtm_dem', 'sentinel2_l2a', 'landsat_c2_l2', 'esa_worldcover')),
    acquisition_date   DATE NOT NULL,
    crs                TEXT NOT NULL,
    resolution_m       NUMERIC NOT NULL CHECK (resolution_m > 0),
    storage_location   TEXT NOT NULL,
    spatial_extent     geometry(Polygon, 4326) NOT NULL,
    provenance_id      UUID NOT NULL REFERENCES data_provenance_record(provenance_id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_raster_extent_srid CHECK (ST_SRID(spatial_extent) = 4326),
    CONSTRAINT chk_raster_extent_valid CHECK (ST_IsValid(spatial_extent))
);

CREATE INDEX idx_raster_asset_extent_gist ON environmental_raster_asset USING GIST (spatial_extent);
CREATE INDEX idx_raster_asset_source_code ON environmental_raster_asset (source_code);
CREATE INDEX idx_raster_asset_acquisition_date ON environmental_raster_asset (acquisition_date);
CREATE INDEX idx_raster_asset_provenance_id ON environmental_raster_asset (provenance_id);

CREATE TRIGGER trg_raster_asset_no_update
    BEFORE UPDATE ON environmental_raster_asset
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE environmental_raster_asset IS
    'EnvironmentalRasterAsset entity (EDD Section 16). One row per ingested SRTM/Sentinel-2/Landsat C2/ESA WorldCover tile or scene.';
COMMENT ON COLUMN environmental_raster_asset.acquisition_date IS
    'Observation time (Section 26). For ESA WorldCover this represents the product epoch (2020 v100 or 2021 v200), not a precise acquisition date (Section 13).';
COMMENT ON COLUMN environmental_raster_asset.storage_location IS
    'Opaque reference to the raster file in the object/file store. Storage technology is Not specified in EDD Section 16/21 — TODO once decided.';

-- ============================================================================
-- 0007_meteorological_observation.sql
-- ============================================================================
-- VEKTRA Database — Migration 0007
-- meteorological_observation: MeteorologicalObservation entity
-- (EDD Section 16), Environmental Observation Layer (Section 15).
-- One row per (location, timestamp, variable) reading retrieved from
-- Open-Meteo.
--
-- Modeled as one row per variable (rather than fixed columns per
-- variable) because EDD Section 13 gives only an open-ended example list
-- of variables ("temperature, humidity, wind, solar radiation, etc.") and
-- does not enumerate the exact set VEKTRA will ingest. A fixed-column
-- design would require inventing that closed set; this design does not.
--
-- TODO: the exact set of Open-Meteo variables to ingest, and the unit
-- convention for variable_unit, are Not specified in EDD Section 13 and
-- must be finalized during ingestion implementation (Section 14).

CREATE TABLE meteorological_observation (
    met_observation_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_code             TEXT NOT NULL REFERENCES data_source(source_code)
                                 CHECK (source_code = 'open_meteo'),
    observation_timestamp   TIMESTAMPTZ NOT NULL,
    location                 geometry(Point, 4326) NOT NULL,
    variable_name            TEXT NOT NULL,
    variable_value           NUMERIC NOT NULL,
    variable_unit            TEXT NOT NULL,
    provenance_id            UUID NOT NULL REFERENCES data_provenance_record(provenance_id),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_met_location_srid CHECK (ST_SRID(location) = 4326),
    CONSTRAINT uq_met_observation
        UNIQUE (location, observation_timestamp, variable_name, provenance_id)
);

CREATE INDEX idx_met_observation_location_gist ON meteorological_observation USING GIST (location);
CREATE INDEX idx_met_observation_timestamp ON meteorological_observation (observation_timestamp);
CREATE INDEX idx_met_observation_variable_name ON meteorological_observation (variable_name);
CREATE INDEX idx_met_observation_provenance_id ON meteorological_observation (provenance_id);

CREATE TRIGGER trg_met_observation_no_update
    BEFORE UPDATE ON meteorological_observation
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE meteorological_observation IS
    'MeteorologicalObservation entity (EDD Section 16). One row per variable reading at a representative point (Section 13).';
COMMENT ON COLUMN meteorological_observation.location IS
    'Representative point queried, per Section 13: "the bounding box or representative point(s) within it". Native source resolution is far coarser than a building footprint (Section 13, 37) — must be disclosed as such wherever used.';

-- ============================================================================
-- 0008_simulation_run.sql
-- ============================================================================
-- VEKTRA Database — Migration 0008
-- simulation_run: SimulationRun entity (EDD Section 16), Derived/Computed
-- Layer (Section 15). One row per execution of the deterministic
-- simulation engine, whether a baseline run or a scenario-derived run
-- (Section 11).
--
-- Per Section 17, a run is fully determined by (code_version,
-- configuration_version, input dataset version identifiers) — those
-- identity columns must never change after creation, which is why this
-- table is NOT fully append-only like the others: it needs a mutable
-- `status` lifecycle (Section 16: "status"; Section 21: "Trigger and query
-- the status of a simulation run") while its identity columns stay fixed.
-- fn_guard_simulation_run_update() enforces exactly that split.
--
-- baseline_run_id is a self-reference used only by scenario runs, to
-- record "the baseline run identifier it was derived from" (Section 11).

CREATE TABLE simulation_run (
    run_id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code_version           TEXT NOT NULL,
    configuration_version  TEXT NOT NULL,
    run_type               TEXT NOT NULL CHECK (run_type IN ('baseline', 'scenario')),
    baseline_run_id        UUID REFERENCES simulation_run(run_id),
    status                 TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    started_at             TIMESTAMPTZ,
    completed_at           TIMESTAMPTZ,
    error_message          TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_run_baseline_reference CHECK (
        (run_type = 'baseline' AND baseline_run_id IS NULL) OR
        (run_type = 'scenario' AND baseline_run_id IS NOT NULL)
    )
);

CREATE OR REPLACE FUNCTION fn_guard_simulation_run_update()
RETURNS trigger AS $$
BEGIN
    IF NEW.code_version          IS DISTINCT FROM OLD.code_version OR
       NEW.configuration_version IS DISTINCT FROM OLD.configuration_version OR
       NEW.run_type              IS DISTINCT FROM OLD.run_type OR
       NEW.baseline_run_id       IS DISTINCT FROM OLD.baseline_run_id OR
       NEW.created_at            IS DISTINCT FROM OLD.created_at
    THEN
        RAISE EXCEPTION
            'simulation_run identity columns (code_version, configuration_version, run_type, baseline_run_id, created_at) are immutable per EDD Section 17 (run_id: %)',
            OLD.run_id;
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_guard_simulation_run_update() IS
    'Allows only status/started_at/completed_at/error_message to change on a simulation_run; identity columns are frozen at creation (EDD Section 17).';

CREATE TRIGGER trg_simulation_run_guard_update
    BEFORE UPDATE ON simulation_run
    FOR EACH ROW EXECUTE FUNCTION fn_guard_simulation_run_update();

CREATE INDEX idx_simulation_run_status ON simulation_run (status);
CREATE INDEX idx_simulation_run_type ON simulation_run (run_type);
CREATE INDEX idx_simulation_run_baseline_run_id ON simulation_run (baseline_run_id);
CREATE INDEX idx_simulation_run_code_version ON simulation_run (code_version);

COMMENT ON TABLE simulation_run IS
    'SimulationRun entity (EDD Section 16, 17). One row per baseline or scenario simulation execution.';
COMMENT ON COLUMN simulation_run.configuration_version IS
    'Versioned run configuration identifier (Section 17, 27). No separate configuration table is defined — EDD Section 16/17 describe this only as a version identifier, not a distinct entity.';

-- ============================================================================
-- 0009_simulation_run_input_dataset.sql
-- ============================================================================
-- VEKTRA Database — Migration 0009
-- simulation_run_input_dataset: join table recording the exact set of
-- dataset versions (data_provenance_record rows) consumed by a given
-- simulation run.
--
-- This table is what realizes, at the schema level:
--   - FR-12: "record, for every simulation run, the exact input dataset
--     versions and code version used, sufficient to reproduce the run."
--   - Section 17, point 3: a run "writes results tagged with a run
--     identifier, the code version, and the exact input version
--     identifiers used."
--   - The "dataset versions" tracking requirement given for this task —
--     see db/README.md for why this is a join table rather than a
--     duplicate "dataset_version" table (also explained in migration
--     0004).
--
-- A run typically consumes multiple dataset versions at once (an OSM
-- batch, an SRTM tile, a Sentinel-2 scene, a Landsat scene, a WorldCover
-- tile, an Open-Meteo pull), hence a many-to-many join rather than a
-- single foreign key on simulation_run.

CREATE TABLE simulation_run_input_dataset (
    run_id         UUID NOT NULL REFERENCES simulation_run(run_id),
    provenance_id  UUID NOT NULL REFERENCES data_provenance_record(provenance_id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (run_id, provenance_id)
);

CREATE INDEX idx_run_input_dataset_provenance_id ON simulation_run_input_dataset (provenance_id);

CREATE TRIGGER trg_run_input_dataset_no_update
    BEFORE UPDATE ON simulation_run_input_dataset
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE simulation_run_input_dataset IS
    'Join of simulation_run to the exact data_provenance_record rows (dataset versions) it consumed. Implements FR-12 and EDD Section 17 reproducibility.';

-- ============================================================================
-- 0010_scenario.sql
-- ============================================================================
-- VEKTRA Database — Migration 0010
-- scenario: Scenario entity (EDD Section 16), Scenario/Overlay Layer
-- (Section 15). A named, versioned set of attribute-level overrides
-- applied on top of one baseline simulation run (Section 19).
--
-- Per FR-8/FR-9, a scenario is first defined (baseline_run_id, name,
-- overrides) and only later executed, producing a derived SimulationRun
-- (Section 16: "produces exactly one derived SimulationRun"). That means
-- derived_run_id starts NULL and is set exactly once, after execution —
-- the one legitimate mutation this otherwise append-only table permits
-- (Section 19: "Scenarios are retained indefinitely (append-only)").
-- fn_guard_scenario_update() enforces that.

CREATE TABLE scenario (
    scenario_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    baseline_run_id  UUID NOT NULL REFERENCES simulation_run(run_id),
    derived_run_id   UUID REFERENCES simulation_run(run_id),
    name             TEXT NOT NULL,
    description      TEXT,
    created_by       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_scenario_derived_not_baseline
        CHECK (derived_run_id IS NULL OR derived_run_id <> baseline_run_id)
);

CREATE OR REPLACE FUNCTION fn_guard_scenario_update()
RETURNS trigger AS $$
BEGIN
    IF NEW.baseline_run_id IS DISTINCT FROM OLD.baseline_run_id OR
       NEW.name            IS DISTINCT FROM OLD.name OR
       NEW.description     IS DISTINCT FROM OLD.description OR
       NEW.created_by       IS DISTINCT FROM OLD.created_by OR
       NEW.created_at        IS DISTINCT FROM OLD.created_at OR
       (OLD.derived_run_id IS NOT NULL AND NEW.derived_run_id IS DISTINCT FROM OLD.derived_run_id)
    THEN
        RAISE EXCEPTION
            'scenario is append-only per EDD Section 19, except for setting derived_run_id exactly once (scenario_id: %)',
            OLD.scenario_id;
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_guard_scenario_update() IS
    'Allows only a one-time transition of derived_run_id from NULL to a value, once a scenario has been executed (EDD Section 19).';

CREATE TRIGGER trg_scenario_guard_update
    BEFORE UPDATE ON scenario
    FOR EACH ROW EXECUTE FUNCTION fn_guard_scenario_update();

CREATE INDEX idx_scenario_baseline_run_id ON scenario (baseline_run_id);
CREATE INDEX idx_scenario_derived_run_id ON scenario (derived_run_id);

COMMENT ON TABLE scenario IS
    'Scenario entity (EDD Section 16, 19). Never modifies baseline geometry or baseline records; overrides are resolved at simulation time (Section 15).';
COMMENT ON COLUMN scenario.created_by IS
    'Free-text identifier of who/what created the scenario, for audit logging (Section 30). Authentication/authorization model is Not specified in EDD Section 23 — no users table is assumed or invented.';

-- ============================================================================
-- 0011_scenario_override.sql
-- ============================================================================
-- VEKTRA Database — Migration 0011
-- scenario_override: child of scenario, realizing Section 16's "ordered
-- list of attribute overrides (each referencing a building identifier, an
-- attribute name, and an override value)". sequence_number preserves the
-- stated ordering.
--
-- Per Section 19, "only attributes referenced by the Heat Exposure Index
-- methodology (Section 18) may be overridden", and per Section 22 the
-- scenario editor is "scoped to a defined set of overridable attributes."
-- That set itself is never enumerated anywhere in the EDD, so
-- attribute_name is left as free TEXT rather than a CHECK-constrained
-- enum or foreign key to an attribute catalog.
--
-- TODO: the closed set of overridable attributes, and the value type/
-- validation rules for override_value, are Not specified in EDD Section
-- 18/19/22 and must be defined before the Scenario Subsystem (Section 10
-- #5) can enforce them. Application-level validation is expected to
-- narrow this once that set is defined; it is not invented here.

CREATE TABLE scenario_override (
    override_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scenario_id       UUID NOT NULL REFERENCES scenario(scenario_id),
    building_id       UUID NOT NULL REFERENCES building(building_id),
    sequence_number   INTEGER NOT NULL CHECK (sequence_number >= 0),
    attribute_name    TEXT NOT NULL,
    override_value    TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_scenario_override_sequence UNIQUE (scenario_id, sequence_number),
    CONSTRAINT uq_scenario_override_attribute UNIQUE (scenario_id, building_id, attribute_name)
);

CREATE INDEX idx_scenario_override_scenario_id ON scenario_override (scenario_id);
CREATE INDEX idx_scenario_override_building_id ON scenario_override (building_id);

CREATE TRIGGER trg_scenario_override_no_update
    BEFORE UPDATE ON scenario_override
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE scenario_override IS
    'Ordered attribute-level overrides belonging to a scenario (EDD Section 16, 19). Never modifies the building row it references.';
COMMENT ON COLUMN scenario_override.override_value IS
    'Stored as TEXT: the EDD defines no fixed schema for override value types across attributes. Type coercion is an application-level concern (Section 19).';

-- ============================================================================
-- 0012_heat_exposure_result.sql
-- ============================================================================
-- VEKTRA Database — Migration 0012
-- heat_exposure_result: HeatExposureResult entity (EDD Section 16),
-- Derived/Computed Layer (Section 15). One row per (simulation_run,
-- building) pair — "a Building has many HeatExposureResults (one per
-- SimulationRun in which it participated); a SimulationRun has many
-- HeatExposureResults" (Section 16, Key relationships).
--
-- index_value is nullable. Section 18 ("Combination") states the
-- normalization method and weights that would produce a single composite
-- value are "Requires future implementation" and "must be defined,
-- justified, and version-controlled before the index is presented as
-- anything other than a set of independent, per-factor values." Until
-- that methodology exists, a run may only populate per-factor values (see
-- heat_exposure_factor_value, migration 0013) and leave index_value NULL.

CREATE TABLE heat_exposure_result (
    result_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id        UUID NOT NULL REFERENCES simulation_run(run_id),
    building_id   UUID NOT NULL REFERENCES building(building_id),
    index_value   NUMERIC,
    computed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_result_run_building UNIQUE (run_id, building_id)
);

CREATE INDEX idx_result_run_id ON heat_exposure_result (run_id);
CREATE INDEX idx_result_building_id ON heat_exposure_result (building_id);

CREATE TRIGGER trg_result_no_update
    BEFORE UPDATE ON heat_exposure_result
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE heat_exposure_result IS
    'HeatExposureResult entity (EDD Section 16). One row per building per simulation run.';
COMMENT ON COLUMN heat_exposure_result.index_value IS
    'Composite Heat Exposure Index. NULL until the combination methodology (Section 18) is defined; TODO per that section.';

-- ============================================================================
-- 0013_heat_exposure_factor_value.sql
-- ============================================================================
-- VEKTRA Database — Migration 0013
-- heat_exposure_factor_value: child of heat_exposure_result, realizing
-- Section 16's "per-factor contributing values (Section 18)" for
-- HeatExposureResult. Normalized into its own table (one row per factor
-- per result) rather than five wide nullable columns, so that adding or
-- retiring a candidate factor never requires a schema migration.
--
-- factor_key is constrained to exactly the five candidate conceptual
-- factors named in EDD Section 18. is_computable operationalizes Section
-- 18's explicit instruction for the exposure/shading factor — generalized
-- here to any factor — that when a factor cannot be computed from
-- available data, it "must be explicitly marked as 'not computable with
-- available data' rather than approximated with invented values."

CREATE TABLE heat_exposure_factor_value (
    factor_value_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    result_id         UUID NOT NULL REFERENCES heat_exposure_result(result_id),
    factor_key        TEXT NOT NULL CHECK (factor_key IN (
                            'thermal_signature',
                            'vegetation_land_cover',
                            'morphology_density',
                            'exposure_shading',
                            'meteorological_context'
                        )),
    factor_value      NUMERIC,
    is_computable     BOOLEAN NOT NULL DEFAULT TRUE,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_factor_value_per_result UNIQUE (result_id, factor_key),
    CONSTRAINT chk_factor_value_computable
        CHECK (is_computable OR factor_value IS NULL)
);

CREATE INDEX idx_factor_value_result_id ON heat_exposure_factor_value (result_id);
CREATE INDEX idx_factor_value_factor_key ON heat_exposure_factor_value (factor_key);

CREATE TRIGGER trg_factor_value_no_update
    BEFORE UPDATE ON heat_exposure_factor_value
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_update();

COMMENT ON TABLE heat_exposure_factor_value IS
    'Per-factor contributing values for a HeatExposureResult (EDD Section 16, 18).';
COMMENT ON COLUMN heat_exposure_factor_value.is_computable IS
    'FALSE marks a factor as "not computable with available data" per EDD Section 18, instead of approximating it with an invented value.';
COMMENT ON COLUMN heat_exposure_factor_value.notes IS
    'Free-text explanation, e.g. why exposure_shading was not computable for a given building (insufficient OSM height coverage, Section 13/18).';

-- ============================================================================
-- 0014_roles_and_grants.sql
-- ============================================================================
-- VEKTRA Database — Migration 0014
-- Least-privilege database roles per service (EDD Section 33: "Database
-- access: least-privilege database roles per service (e.g., the API layer
-- should not have the same privileges as the ingestion/simulation jobs)").
--
-- These are group roles (NOLOGIN). Actual application login users must be
-- created and granted membership in the appropriate role separately,
-- through a secrets-managed provisioning process — never with a
-- hardcoded password committed to version control (Section 33, "Secrets
-- management: environment variables or a secrets manager, never
-- hardcoded values in the repository").

CREATE ROLE vektra_ingestion NOLOGIN;
CREATE ROLE vektra_simulation NOLOGIN;
CREATE ROLE vektra_backend_api NOLOGIN;

-- Ingestion Subsystem (Section 10 #1, Section 14): writes raw ingested
-- data and its provenance only. Never touches derived results or scenarios.
GRANT SELECT, INSERT ON data_source TO vektra_ingestion;
GRANT SELECT, INSERT ON data_provenance_record TO vektra_ingestion;
GRANT SELECT, INSERT ON building TO vektra_ingestion;
GRANT SELECT, INSERT ON environmental_raster_asset TO vektra_ingestion;
GRANT SELECT, INSERT ON meteorological_observation TO vektra_ingestion;

-- Simulation Subsystem (Section 10 #4, Section 17): reads canonical data
-- and scenario overlays, writes run status and derived results. Also
-- resolves scenario overlays at simulation time (Section 15), so it is
-- the role that sets scenario.derived_run_id once a scenario run completes.
GRANT SELECT ON data_source, data_provenance_record, building,
    environmental_raster_asset, meteorological_observation, scenario,
    scenario_override TO vektra_simulation;
GRANT SELECT, INSERT, UPDATE ON simulation_run TO vektra_simulation;
GRANT SELECT, INSERT ON simulation_run_input_dataset TO vektra_simulation;
GRANT SELECT, INSERT ON heat_exposure_result TO vektra_simulation;
GRANT SELECT, INSERT ON heat_exposure_factor_value TO vektra_simulation;
GRANT UPDATE (derived_run_id) ON scenario TO vektra_simulation;

-- API Subsystem (Section 10 #7, Section 21, 23): read access to
-- everything it serves (FR-11); write access limited to scenario
-- definition (FR-8). The API layer never writes canonical geometry,
-- environmental data, or simulation results directly (Section 9, 11).
GRANT SELECT ON data_source, data_provenance_record, building,
    environmental_raster_asset, meteorological_observation, simulation_run,
    simulation_run_input_dataset, heat_exposure_result,
    heat_exposure_factor_value, scenario, scenario_override
    TO vektra_backend_api;
GRANT INSERT ON scenario, scenario_override TO vektra_backend_api;

-- TODO: whether the backend API directly INSERTs a simulation_run row to
-- "trigger" a run (FR-9, Section 21: "Trigger and query the status of a
-- simulation run") or whether triggering is mediated by a job queue owned
-- by the Scenario/Simulation Subsystem is Not specified in EDD Section
-- 21/23. No INSERT grant on simulation_run is given to vektra_backend_api
-- until this is resolved, to avoid inventing that mechanism here.

-- 0015_era5_meteorological_source.sql

ALTER TABLE meteorological_observation
    DROP CONSTRAINT meteorological_observation_source_code_check;

ALTER TABLE meteorological_observation
    ADD CONSTRAINT meteorological_observation_source_code_check
        CHECK (source_code IN ('open_meteo', 'era5'));

